# Generated by Django 4.2.16 on 2026-02-18 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(default=90)),
                ('summary', models.TextField(blank=True, default='', verbose_name='خلاصه داستان')),
                ('genre', models.CharField(blank=True, default='', max_length=100, verbose_name='ژانر')),
                ('director', models.CharField(blank=True, default='', max_length=100, verbose_name='کارگردان')),
                ('release_year', models.CharField(blank=True, default='', max_length=4, verbose_name='سال ساخت')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters/', verbose_name='پوستر فیلم')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('reserved_seats', models.TextField(blank=True, default='')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='core.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='core.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('NORMAL', 'Normal'), ('VIP', 'VIP')], default='NORMAL', max_length=10)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('seat_numbers', models.CharField(blank=True, default='', max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tracking_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.showtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gte', 0)), name='showtime_capacity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.CheckConstraint(check=models.Q(('reserved_count__gte', 0)), name='showtime_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.CheckConstraint(check=models.Q(('reserved_count__lte', models.F('capacity'))), name='showtime_reserved_lte_capacity'),
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.CheckConstraint(check=models.Q(('base_price__gte', 0)), name='showtime_base_price_non_negative'),
        ),
    ]
