# Generated by Django 4.2.16 on 2026-02-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='capacity',
            field=models.PositiveIntegerField(default=100, verbose_name='ظرفیت سالن'),
        ),
    ]
