# Generated by Django 4.2.16 on 2026-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cinema_capacity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.UniqueConstraint(fields=('cinema', 'movie', 'start_at'), name='unique_movie_screening_per_cinema'),
        ),
    ]
