# Generated by Django 4.2.16 on 2026-02-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_showtime_unique_movie_screening_per_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='بازیگران'),
        ),
    ]
