# Generated by Django 4.2.16 on 2026-02-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movie_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='blocked_seats',
            field=models.TextField(blank=True, default='', verbose_name='صندلی\u200cهای مسدود شده'),
        ),
    ]
